# Site
name: Abdur Rahman
description: Just another website
meta_description: Just another website
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'abdur.rahman.giki@gmail.com'
google_analytics: UA-103662447-9
disqus: abdurrahman
sharethis:

# Authors
authors:
  john:
    name: Abdur
    display_name: Abdur Rahman
    image: /assets/images/john.jpg
    email: abdur.rahman.giki@gmail.com
    web: abdurrahman.tk
    twitter:
    description: Hi, I am Abdur Rahman.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: john
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: Abdur Rahman
links:
    - https://twitter.com/
    - https://www.facebook.com/manikhan29/
    - https://www.linkedin.com/
    - https://github.com/
